apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: directx-device-plugin
  name: directx-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: directx-device-plugin
  template:
    metadata:
      labels:
        k8s-app: directx-device-plugin
    spec:
      hostNetwork: true
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\SYSTEM"
      containers:
        - name: directx-device-plugin
          image: mcr.microsoft.com/aks/aks-windows-gpu-device-plugin:0.0.2
          env:
            - name: "DIRECTX_GPU_MATCH_NAME"
              value: "nvidia"

          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
      nodeSelector:
        kubernetes.io/os: windows
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
